### ISSUE TITLE
Volume level not update when using mouse to change

### ISSUE THREAD

**Issue by hthuong09** [jaagr/lemonbuddy#14]
The volume level actually change but the level display on the bar would not change.
It works fine when I use keyboard (self-wrote external script using amixer)

**Comment by jaagr** [comment]
I will see if I can replicate the issue, because it's working for me using two different setups/machines.

**Comment by jaagr** [comment]
I suspect that it has to do with the `headphone_mixer`, which is still WIP.

**Comment by jaagr** [comment]
I just pushed a fix for the headphone part. Now mute and volume changes should affect the correct mixer depending on weather the headphones are plugged in or not.

This probably won't fix your issue though.

**Comment by jaagr** [comment]
Could you post the output of the following

~~~ bash
$ amixer controls
$ amixer scontrols
~~~

plus the volume section in your config.

**Comment by hthuong09** [comment]
Sorry, I was not at my laptop. Here is the output:
`$ amixer controls`

```
numid=4,iface=MIXER,name='Master Playback Switch'
numid=3,iface=MIXER,name='Master Playback Volume'
numid=2,iface=MIXER,name='Capture Switch'
numid=1,iface=MIXER,name='Capture Volume'
```

`$ amixer scontrols`
```
Simple mixer control 'Master',0
Simple mixer control 'Capture',0
```

Volume config
```
[module/volume]
type = internal/volume
speaker_mixer = Speaker
headphone_mixer = Headphone
headphone_control_numid = 9

format:volume = <ramp:volume> <label:volume>
label:muted =   muted
label:muted:foreground = #66

ramp:volume:0 = 
ramp:volume:1 = 
ramp:volume:2 = 
ramp:volume:3 = 
```

I will try update to the latest source and see if error still occur.

**Comment by jaagr** [comment]
OK, I need to make the headphone stuff optional.

**Comment by jaagr** [comment]
You need to change the values in your config.

Remove `headphone_mixer = Headphone` and `headphone_control_numid = 9` and `speaker_mixer = Speaker`

You only have the Master mixer which is used by default in the code.

I will push a fix in a few minutes that will allow you to remove the headphone values.

**Comment by jaagr** [comment]
I also managed to replicate the bug now, which is good.
