### ISSUE TITLE
Battery module doesn't update

### ISSUE THREAD

**Issue by platipo** [jaagr/lemonbuddy#140]
I recently noticed that after one of last updates the battery module stoppend updating after boot, indeed it's stuck on the boot state even if i plug/unplug the power cord.
Config:
```
[module/battery]
type = internal/battery
full-at = 98
battery = BAT0
adapter = AC

format-charging = <animation-charging>   <label-charging> 
format-discharging = <ramp-capacity> <label-discharging>
format-full = <ramp-capacity> <label-full>

ramp-capacity-0 =  
ramp-capacity-0-foreground = #f53c3c
ramp-capacity-1 =  
ramp-capacity-1-foreground = #ffa900
ramp-capacity-2 =  
ramp-capacity-3 =  
ramp-capacity-4 =  

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate_ms = 750
```

**Comment by sconos** [comment]
Hey, I guess you updated from 1.X - there were a few changes in the configuration, see: 
https://github.com/jaagr/lemonbuddy/wiki/2.0.0---breaking-changes

I hope that helps :)

**Comment by platipo** [comment]
Thank @sconos for the useful link, but I upgraded like two days ago from the prev version. 
By the way I fixed last line to
```
animation-charging-framerate = 750
```
But it doesn't seem to work.

**Comment by sconos** [comment]
Okay.. Have you tried running the bar with the battery module from commandline and logging enabled? Maybe there's some useful output.. 

Cheers

**Comment by jaagr** [comment]
Hi, the bug should be fixed

**Comment by Vintodrimmer** [comment]
Still doesn't work for me (version 2.11.12-1 from AUR).

It shows the correct value when I start the system or come out of suspend, but it doesn't update at all.

**Comment by jaagr** [comment]
@Vintodrimmer it should work with the last update.. please verify

**Comment by BenoitAverty** [comment]
It's fixed for me. Thanks again for your reactivity, you rock.

**Comment by BenoitAverty** [comment]
Wait, actually it doesn't. I was doing checks manually and I noticed the battery module only updates when lemonbuddy starts, or when I do `cat /sys/class/power_supply/BAT0/capacity`. It doesn't update on its own.

**Comment by jaagr** [comment]
could you launch with `-l info` and see if the fallback polling gets disabled..

**Comment by jaagr** [comment]
and make sure you're using the last version

**Comment by BenoitAverty** [comment]
Here's the output : 
```
* Starting application
* Starting event loop
* Starting module/date
* Starting module/volume
* Starting module/network
* Starting module/battery
* module/battery: Polling values (inotify fallback)
* module/battery: Inotify event reported, disable polling fallback...
```

And here's the version : 
```bash
$ pacaur -Q lemonbuddy-git
lemonbuddy-git 2.1.13.r0.g74a04de-1
```

**Comment by jaagr** [comment]
The inotify watches were still listening when triggering the poll.. instead of removing and adding them I added a flag to tell if the event is fake or not..

**Comment by jaagr** [comment]
I think we should make this a setting instead.. because other programs can trigger an event (in which case the polling would get disabled)

**Comment by jaagr** [comment]
ok, now polling is enabled by default.. and poll if a value haven't been reported for 5s (default).. configured using `poll-interval = ...`

disable polling with `poll-interval = 0` (recommended if you know that inotify events get reported by the system)

**Comment by BenoitAverty** [comment]
It looks like it's working. I'll report back if there is another problem. Thanks again.

**Comment by Vintodrimmer** [comment]
Works great now.

**Comment by platipo** [comment]
Great job! :+1:
